apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - demo-data-job.yaml

helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    releaseName: elasticsearch
    version: 8.5.1
    valuesFile: values.yaml
