replicas: 1
esJavaOpts: "-Xms512m -Xmx512m"
resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
volumeClaimTemplate:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
testFramework:
  enabled: false
tests:
  enabled: false
secret:
  enabled: true
  password: changeme
