apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: https://elasticsearch-master:9200
    isDefault: false
    editable: true
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: changeme
    database: demo-metrics
    jsonData:
      esVersion: 80
      timeField: "@timestamp"
      interval: Daily
      maxConcurrentShardRequests: 5
      logLevelField: "service"
      includeFrozen: false
      tlsSkipVerify: true
